mos_so = """
select
       M.folio,
       M.status,
       M.MOBILE_STATUS,
       M.CREATED_AT,
       M.SUBTOTAL,
       M.payment_schema_identifier,
       M.source,
       U.email,
       U.name,
       U.last_name,
       U.phone_number,
       U.company_name,
       M.SOURCE
from POSTGRES_RDS_PROD_ZEUS.purchases M
JOIN POSTGRES_RDS_PROD_ZEUS.users U
on M.user_id = U.id
where M._FIVETRAN_DELETED = FALSE
    and M.CREATED_AT >= '2022-01-01'
order by M.CREATED_AT desc
"""

ns_so = """
SELECT
       T.TRANSACTION_ID,
       T.TRANID as SO,
       T.RELATED_TRANID as SO_ID,
       T.CREATE_DATE as FECHA_SO,
       T.STATUS,
       T.TRANSACTION_TYPE,
       T.TRANSACTION_EXTID,
       T.MONTO_TICKET,
       T.PAGO_CONTRA_ENTREGA,
       /*E.FULL_NAME,
       E.FIRST_NAME,
       E.LAST_NAME,
       E.PHONE,
       E.EMAIL,*/
       Y.FULL_NAME AS CREATED_BY,
       ORIGEN.ORIGEN_DE_LA_ORDEN_NAME,
       PAGO.MTODO_DEL_PAGO_NAME
FROM NETSUITE_SUITEANALYTICS.TRANSACTIONS T
LEFT JOIN
    NETSUITE_SUITEANALYTICS.ENTITY E on T.ENTITY_ID = E.ENTITY_ID
LEFT JOIN NETSUITE_SUITEANALYTICS.EMPLOYEES Y ON Y.EMPLOYEE_ID = T.CREATED_BY_ID
LEFT JOIN NETSUITE_SUITEANALYTICS.ORIGEN_DE_LA_ORDEN ORIGEN ON T.ORIGEN_ID = ORIGEN.ORIGEN_DE_LA_ORDEN_ID
LEFT JOIN NETSUITE_SUITEANALYTICS.METODO_DEL_PAGO PAGO ON T.METODO_DE_PAGO_ID = PAGO.MTODO_DEL_PAGO_ID
WHERE
      T.TRANSACTION_TYPE in ('Orden de venta')
      --AND A.ACCOUNT_ID in (938, 457)
        and T._FIVETRAN_DELETED = FALSE
        and T.CREATE_DATE >= '2022-01-01'
ORDER BY
         T.CREATE_DATE DESC
"""


ns_odbc_so = """
SELECT
       T.TRANSACTION_ID,
       T.TRANID as SO,
       T.RELATED_TRANID as SO_ID,
       T.TRANDATE as FECHA_SO,
       T.STATUS,
       T.TRANSACTION_TYPE,
       T.TRANSACTION_EXTID,
       T.MONTO_TICKET,
       T.PAGO_CONTRA_ENTREGA,
       /*E.FULL_NAME,
       E.FIRST_NAME,
       E.LAST_NAME,
       E.PHONE,
       E.EMAIL,*/
       Y.FULL_NAME AS CREATED_BY,
       ORIGEN.ORIGEN_DE_LA_ORDEN_NAME,
       PAGO.MTODO_DEL_PAGO_NAME
FROM TRANSACTIONS T
LEFT JOIN
    ENTITY E on T.ENTITY_ID = E.ENTITY_ID
LEFT JOIN EMPLOYEES Y ON Y.EMPLOYEE_ID = T.CREATED_BY_ID
LEFT JOIN ORIGEN_DE_LA_ORDEN ORIGEN ON T.ORIGEN_ID = ORIGEN.ORIGEN_DE_LA_ORDEN_ID
LEFT JOIN MÉTODO_DEL_PAGO PAGO ON T.METODO_DE_PAGO_ID = PAGO.MTODO_DEL_PAGO_ID
WHERE
      T.TRANSACTION_TYPE in ('Orden de venta')
      --AND A.ACCOUNT_ID in (938, 457)
        and T.CREATE_DATE >= '2022-01-01'
ORDER BY
         T.CREATE_DATE DESC
"""


ns_sf_po = """
SELECT
       T.TRANSACTION_ID,
       --L.TRANSACTION_LINE_ID::INTEGER AS TRANSACTION_LINE_ID,
       T.TRANID as SO,
       T.RELATED_TRANID as PO_ID,
       T.PO_NUMBER,
       T.TRANDATE as FECHA_PO,
       T.PO__PROYECTO,
       T.STATUS,
       T.TRANSACTION_TYPE,
       T.TRANSACTION_EXTID,
       P.NAME,
       --L.HS_CODE,
       E.FULL_NAME,
       E.PHONE,
       E.EMAIL,
       --I.FULL_NAME as NOMBRE_DE_PRODUCTO,
       --I.DISPLAYNAME AS DESCRIPCION_ARTICULO,
       --I.ITEM_ID,
       --I.SKU_FUXI,
       --I.PURCHASEDESCRIPTION,
       --C.LIST_ITEM_NAME as CATEGORIA_DE_PRODUCTO,
       --I.NAME AS CODIGO_EAN,
       --ABS(L.ITEM_COUNT) AS CANTIDAD,
       ABS(L.AMOUNT) AS AMOUNT,
       ABS(L.AMOUNT_FOREIGN) AS FOREING_AMOUNT,
       --T.CREATED_BY_ID,
       Y.FULL_NAME AS CREATED_BY,
       --A.FULL_NAME AS ACCOUNT_NAME,
       A.ACCOUNT_ID
        ,T.INCOTERM
        --,P.PAYMENT_TERMS_EXTID
FROM NETSUITE_SUITEANALYTICS.TRANSACTIONS T
JOIN NETSUITE_SUITEANALYTICS.TRANSACTION_LINES L ON T.TRANSACTION_ID = L.TRANSACTION_ID
LEFT JOIN
    NETSUITE_SUITEANALYTICS.PAYMENT_TERMS P on T.PAYMENT_TERMS_ID = P.PAYMENT_TERMS_ID
LEFT JOIN
    NETSUITE_SUITEANALYTICS.ENTITY E on T.ENTITY_ID = E.ENTITY_ID
LEFT JOIN NETSUITE_SUITEANALYTICS.EMPLOYEES Y ON Y.EMPLOYEE_ID = T.CREATED_BY_ID
LEFT JOIN NETSUITE_SUITEANALYTICS.EMPLOYEES Y2 ON Y2.EMPLOYEE_ID = T.SALES_REP_ID
LEFT JOIN NETSUITE_SUITEANALYTICS.ACCOUNTS A ON A.ACCOUNT_ID=L.ACCOUNT_ID
LEFT JOIN NETSUITE_SUITEANALYTICS.INVENTORY_ITEMS I ON I.ITEM_ID = L.ITEM_ID
LEFT JOIN NETSUITE_SUITEANALYTICS.CATEGORIA_DE_PRODUCTO C on I.CATEGORA_DE_PRODUCTO_ID = C.LIST_ID
LEFT JOIN NETSUITE_SUITEANALYTICS.COMPANIES CN ON CN.COMPANY_ID = L.COMPANY_ID
WHERE
      A.ACCOUNT_ID in (118)
      AND T.TRANSACTION_TYPE in ('Pedido')
      AND L.TRANSACTION_ID IN (
    SELECT DISTINCT(TRANSACTION_ID)
    FROM NETSUITE_SUITEANALYTICS.TRANSACTION_LINES L
    LEFT JOIN NETSUITE_SUITEANALYTICS.ACCOUNTS A ON A.ACCOUNT_ID=L.ACCOUNT_ID
    WHERE L.ACCOUNT_ID = 938
    )
order by T.TRANDATE desc;
"""
